[2024-07-03T18:57:43.497+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:57:43.517+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:57:43.522+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T18:57:43.549+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T18:57:43.566+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-03T18:57:43.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnbyp19hh']
[2024-07-03T18:57:43.583+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask film_actor
[2024-07-03T18:57:43.743+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host df9727a9ba29
[2024-07-03T18:57:44.593+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T18:57:44.595+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T18:57:44.597+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T18:57:44.601+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T18:57:44.660+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-03T18:57:44.661+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T18:57:44.692+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T185743, end_date=20240703T185744
[2024-07-03T18:57:44.782+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T18:57:44.862+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T18:59:06.260+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:59:06.294+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:59:06.314+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T18:59:06.349+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T18:59:06.360+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-03T18:59:06.380+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6ag2u6m6']
[2024-07-03T18:59:06.395+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film_actor
[2024-07-03T18:59:06.588+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 1eca196ca799
[2024-07-03T18:59:07.570+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T18:59:07.575+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T18:59:07.589+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T18:59:07.594+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T18:59:07.633+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T18:59:07.674+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T185906, end_date=20240703T185907
[2024-07-03T18:59:07.718+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 96)
[2024-07-03T18:59:07.736+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T18:59:07.793+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:04:29.101+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:04:29.170+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:04:29.183+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:04:29.222+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:04:29.250+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpedbbso63']
[2024-07-03T19:04:29.271+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask film_actor
[2024-07-03T19:04:29.252+0000] {standard_task_runner.py:60} INFO - Started process 105 to run task
[2024-07-03T19:04:29.406+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 1e717689b816
[2024-07-03T19:04:30.497+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:04:30.500+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:04:30.519+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:04:30.541+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:04:30.715+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:04:30.942+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T190429, end_date=20240703T190430
[2024-07-03T19:04:30.990+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 105)
[2024-07-03T19:04:31.069+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:04:31.161+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:07:23.710+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:07:23.721+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:07:23.723+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:07:23.755+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:07:23.778+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-07-03T19:07:23.807+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvb46i29q']
[2024-07-03T19:07:23.831+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask film_actor
[2024-07-03T19:07:24.006+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 543ad6da9cd9
[2024-07-03T19:07:25.229+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:07:25.234+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:07:25.235+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:07:25.236+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:07:25.257+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:07:25.268+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T190723, end_date=20240703T190725
[2024-07-03T19:07:25.337+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 109)
[2024-07-03T19:07:25.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:07:25.423+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:11:45.016+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:11:45.033+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:11:45.039+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:11:45.076+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:11:45.091+0000] {standard_task_runner.py:60} INFO - Started process 125 to run task
[2024-07-03T19:11:45.105+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqzp5_zwq']
[2024-07-03T19:11:45.119+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask film_actor
[2024-07-03T19:11:45.333+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 7c298ace0001
[2024-07-03T19:11:45.505+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:11:45.510+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:11:45.513+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:11:45.518+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:11:45.519+0000] {logging_mixin.py:188} INFO - film_actor sqltostaging
[2024-07-03T19:11:46.592+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:11:46.617+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T191145, end_date=20240703T191146
[2024-07-03T19:11:46.634+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 125)
[2024-07-03T19:11:46.684+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:11:46.791+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:17:15.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:17:15.651+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:17:15.658+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:17:15.679+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:17:15.687+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-07-03T19:17:15.713+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpothjex7v']
[2024-07-03T19:17:15.731+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask film_actor
[2024-07-03T19:17:15.917+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 55c1c604b2f4
[2024-07-03T19:17:16.907+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:17:16.909+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:17:16.910+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:17:16.911+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:17:16.911+0000] {logging_mixin.py:188} INFO - film_actor sqltostaging
[2024-07-03T19:17:16.911+0000] {logging_mixin.py:188} INFO - sqltostaging film_actor
[2024-07-03T19:17:16.912+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T19:17:16.946+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T191715, end_date=20240703T191716
[2024-07-03T19:17:17.076+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T19:17:17.120+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:21:11.299+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:21:11.347+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:21:11.349+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:21:11.397+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:21:11.409+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-03T19:21:11.444+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp46pa2uvf']
[2024-07-03T19:21:11.475+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask film_actor
[2024-07-03T19:21:11.720+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 048fbe570e70
[2024-07-03T19:21:12.965+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:21:12.968+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:21:12.972+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:21:12.976+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:21:12.980+0000] {logging_mixin.py:188} INFO - film_actor sqltostaging
[2024-07-03T19:21:12.980+0000] {logging_mixin.py:188} INFO - sqltostaging film_actor
[2024-07-03T19:21:12.981+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'sqltostaging' and Stage = 'film_actor'
[2024-07-03T19:21:12.995+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:21:13.008+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T192111, end_date=20240703T192113
[2024-07-03T19:21:13.019+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 95)
[2024-07-03T19:21:13.063+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:21:13.131+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:27:20.752+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:27:20.795+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:27:20.807+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:27:20.868+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:27:20.894+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-07-03T19:27:20.906+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpq_svjv_d']
[2024-07-03T19:27:20.928+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask film_actor
[2024-07-03T19:27:21.063+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host be8a642b7fa1
[2024-07-03T19:27:22.136+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:27:22.140+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:27:22.145+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:27:22.149+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:film_actor
[2024-07-03T19:27:22.151+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'staff' and Stage = 'sqltostaging'
[2024-07-03T19:27:22.183+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table("staff", "sqltostaging")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:27:22.204+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T192720, end_date=20240703T192722
[2024-07-03T19:27:22.211+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 102)
[2024-07-03T19:27:22.232+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:27:22.289+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:31:15.801+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:31:15.826+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:31:15.832+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:31:15.907+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:31:15.925+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-03T19:31:15.935+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm66_hrzm']
[2024-07-03T19:31:15.939+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film_actor
[2024-07-03T19:31:16.083+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 3aa24a0be289
[2024-07-03T19:31:17.111+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:31:17.120+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:31:17.136+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:31:17.142+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:31:17.152+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'staff' and Stage = 'SqlToStaging'
[2024-07-03T19:31:17.195+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-03T19:31:17.197+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T19:31:17.210+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T193115, end_date=20240703T193117
[2024-07-03T19:31:17.294+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T19:31:17.331+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:33:30.695+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:33:30.706+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:33:30.712+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:33:30.734+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:33:30.752+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-03T19:33:30.758+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_nspc3yr']
[2024-07-03T19:33:30.769+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film_actor
[2024-07-03T19:33:30.930+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 90f97448b910
[2024-07-03T19:33:31.926+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:33:31.937+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:33:31.947+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:33:31.948+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:33:31.949+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_actor' and Stage = 'SqlToStaging'
[2024-07-03T19:33:32.018+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:33:32.052+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T193330, end_date=20240703T193332
[2024-07-03T19:33:32.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 95)
[2024-07-03T19:33:32.179+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:33:32.196+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:45:39.320+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:45:39.343+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:45:39.345+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:45:39.378+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:45:39.383+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2024-07-03T19:45:39.392+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpud7mjlvs']
[2024-07-03T19:45:39.412+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask film_actor
[2024-07-03T19:45:39.607+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 2d80eee2aa9e
[2024-07-03T19:45:40.920+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:45:40.921+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:45:40.927+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:45:40.957+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:45:40.978+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_actor' and Stage = 'SqlToStaging'
[2024-07-03T19:45:41.100+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:45:41.156+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T194539, end_date=20240703T194541
[2024-07-03T19:45:41.183+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 143)
[2024-07-03T19:45:41.208+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:45:41.306+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:51:24.194+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:51:24.227+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:51:24.232+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:51:24.263+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:51:24.269+0000] {standard_task_runner.py:60} INFO - Started process 101 to run task
[2024-07-03T19:51:24.293+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpoj2ft9t1']
[2024-07-03T19:51:24.303+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask film_actor
[2024-07-03T19:51:24.497+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host f02b6fe92b0c
[2024-07-03T19:51:25.657+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:51:25.660+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:51:25.666+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:51:25.669+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:51:25.671+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_actor' and Stage = 'SqlToStaging'
[2024-07-03T19:51:25.719+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:51:25.736+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T195124, end_date=20240703T195125
[2024-07-03T19:51:25.756+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 101)
[2024-07-03T19:51:25.787+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:51:25.858+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:57:27.619+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:57:27.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:57:27.677+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:57:27.727+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:57:27.752+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-03T19:57:27.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb15afx4c']
[2024-07-03T19:57:27.833+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask film_actor
[2024-07-03T19:57:27.992+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 94f9954c2898
[2024-07-03T19:57:28.781+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:57:28.786+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:57:28.787+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:57:28.788+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:57:28.790+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_actor' and Stage = 'SqlToStaging'
[2024-07-03T19:57:28.812+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:57:28.851+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T195727, end_date=20240703T195728
[2024-07-03T19:57:28.884+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 97)
[2024-07-03T19:57:28.936+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:57:29.038+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:59:31.835+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:59:31.862+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:59:31.869+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:59:31.941+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_actor> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:59:31.953+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-03T19:59:31.967+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'film_actor', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpntx951h_']
[2024-07-03T19:59:31.974+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask film_actor
[2024-07-03T19:59:32.209+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.film_actor scheduled__2024-07-02T00:00:00+00:00 [running]> on host 091922596b62
[2024-07-03T19:59:33.155+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='film_actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:59:33.161+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:59:33.168+0000] {logging_mixin.py:188} INFO - table: film_actor
[2024-07-03T19:59:33.174+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:film_actor
[2024-07-03T19:59:33.176+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_actor' and Stage = 'SqlToStaging'
[2024-07-03T19:59:33.275+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:59:33.310+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=film_actor, execution_date=20240702T000000, start_date=20240703T195931, end_date=20240703T195933
[2024-07-03T19:59:33.327+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task film_actor (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 99)
[2024-07-03T19:59:33.390+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:59:33.450+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
