[2024-07-10T19:19:12.836+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.844+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.846+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:19:12.860+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:19:12.868+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-10T19:19:12.874+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpftbay9sp']
[2024-07-10T19:19:12.887+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask customer
[2024-07-10T19:19:13.090+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 988357c0810b
[2024-07-10T19:19:14.575+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:19:14.583+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'SqlToStaging'
[2024-07-10T19:19:14.639+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 30, in get_data_from_conf_table
    cur.execute(query)
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
[2024-07-10T19:19:14.695+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T191912, end_date=20240710T191914
[2024-07-10T19:19:14.735+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task customer ('psycopg2.extensions.connection' object has no attribute 'execute'; 93)
[2024-07-10T19:19:14.781+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:19:14.866+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:24:52.005+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.021+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.023+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:24:52.071+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:24:52.090+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-10T19:24:52.105+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp883b7lqu']
[2024-07-10T19:24:52.123+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask customer
[2024-07-10T19:24:52.253+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 1dd842c603c2
[2024-07-10T19:24:53.568+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:24:53.572+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'SqlToStaging'
[2024-07-10T19:24:53.644+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:24:53.680+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T192452, end_date=20240710T192453
[2024-07-10T19:24:53.712+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task customer (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 91)
[2024-07-10T19:24:53.773+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:24:53.806+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:33:52.702+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.713+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.716+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:33:52.771+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:33:52.784+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-10T19:33:52.797+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsdhy29vt']
[2024-07-10T19:33:52.810+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask customer
[2024-07-10T19:33:52.982+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:33:54.328+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:33:54.337+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'SqlToStaging'
[2024-07-10T19:33:54.400+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:33:54.437+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T193352, end_date=20240710T193354
[2024-07-10T19:33:54.500+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task customer (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 93)
[2024-07-10T19:33:54.532+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:33:54.549+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:37:48.225+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.239+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.246+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:37:48.288+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:37:48.298+0000] {standard_task_runner.py:60} INFO - Started process 244 to run task
[2024-07-10T19:37:48.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplx31bxd6']
[2024-07-10T19:37:48.325+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask customer
[2024-07-10T19:37:48.497+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:37:48.728+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:37:48.739+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T19:37:49.710+0000] {logging_mixin.py:188} INFO -    0         1          2       3   ...    11    12            13    14
0  15  customer  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:37:49.745+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T19:37:49.746+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:37:49.747+0000] {logging_mixin.py:188} INFO - table: customer
[2024-07-10T19:37:49.758+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:customer
[2024-07-10T19:37:49.764+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:37:49.782+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T193748, end_date=20240710T193749
[2024-07-10T19:37:49.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:37:49.860+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:39:58.174+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.187+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.194+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:39:58.230+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:39:58.254+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-10T19:39:58.280+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjdjlkacx']
[2024-07-10T19:39:58.314+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask customer
[2024-07-10T19:39:58.507+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 4118dead3d7f
[2024-07-10T19:39:59.329+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:39:59.336+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T19:39:59.640+0000] {logging_mixin.py:188} INFO -    0         1          2       3   ...    11    12            13    14
0  15  customer  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:39:59.647+0000] {logging_mixin.py:188} INFO - incremental
[2024-07-10T19:39:59.658+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:39:59.660+0000] {logging_mixin.py:188} INFO - table: customer
[2024-07-10T19:39:59.661+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:customer
[2024-07-10T19:39:59.664+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:39:59.696+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T193958, end_date=20240710T193959
[2024-07-10T19:39:59.816+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:39:59.881+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:44:02.947+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:02.963+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:02.970+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:44:02.985+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:44:03.001+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-10T19:44:03.003+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgcg9gxfv']
[2024-07-10T19:44:03.016+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask customer
[2024-07-10T19:44:03.187+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host a383c1e8c871
[2024-07-10T19:44:04.062+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:44:04.074+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T19:44:04.578+0000] {logging_mixin.py:188} INFO -    0         1          2       3   ...    11    12            13    14
0  15  customer  dvdrental  public  ...  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:44:04.607+0000] {logging_mixin.py:188} INFO - incremental
[2024-07-10T19:44:04.621+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:44:04.629+0000] {logging_mixin.py:188} INFO - table: customer
[2024-07-10T19:44:04.631+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:customer
[2024-07-10T19:44:04.637+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:44:04.670+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T194402, end_date=20240710T194404
[2024-07-10T19:44:04.739+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:44:04.834+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:53:56.941+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:56.963+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:56.973+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:53:57.008+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:53:57.027+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T19:53:57.051+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyu2der3i']
[2024-07-10T19:53:57.062+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask customer
[2024-07-10T19:53:57.214+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host c340805483c7
[2024-07-10T19:53:58.293+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:53:58.310+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:53:58.322+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T195356, end_date=20240710T195358
[2024-07-10T19:53:58.357+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:53:58.404+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:56:46.684+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.703+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.704+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:56:46.743+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:56:46.761+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T19:56:46.772+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqihnx6nl']
[2024-07-10T19:56:46.804+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask customer
[2024-07-10T19:56:47.038+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host eb5f087f7265
[2024-07-10T19:56:48.018+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:56:48.105+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:56:48.133+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T195646, end_date=20240710T195648
[2024-07-10T19:56:48.210+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:56:48.254+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:00:56.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.675+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.676+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:00:56.725+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:00:56.753+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-07-10T20:00:56.775+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpspcw8u4x']
[2024-07-10T20:00:56.809+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask customer
[2024-07-10T20:00:57.087+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host c8649e4aae44
[2024-07-10T20:00:58.939+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:00:59.091+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
TypeError: some_function() missing 4 required positional arguments: 'schema', 'table', 'fromDate', and 'toDate'
[2024-07-10T20:00:59.172+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T200056, end_date=20240710T200059
[2024-07-10T20:00:59.264+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task customer (some_function() missing 4 required positional arguments: 'schema', 'table', 'fromDate', and 'toDate'; 94)
[2024-07-10T20:00:59.470+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:01:00.071+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:05:21.137+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.156+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.158+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:05:21.191+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:05:21.202+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-10T20:05:21.214+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpese0hsgk']
[2024-07-10T20:05:21.233+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask customer
[2024-07-10T20:05:21.370+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 3f026d601c5c
[2024-07-10T20:05:22.287+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:05:22.363+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'sqltostaging' and Stage = 'customer'
[2024-07-10T20:05:22.439+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 45, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 145, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T20:05:22.507+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T200521, end_date=20240710T200522
[2024-07-10T20:05:22.542+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task customer (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 88)
[2024-07-10T20:05:22.580+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:05:22.608+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:09:18.388+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.410+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.411+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:09:18.456+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:09:18.484+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwzouwr85']
[2024-07-10T20:09:18.496+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask customer
[2024-07-10T20:09:18.484+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T20:09:18.686+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 61a58fe9b448
[2024-07-10T20:09:20.027+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:09:20.089+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:09:20.161+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:09:20.162+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 48, in getDF
    return pd.read_sql(query ,conn.getConnection(source_dbname))
AttributeError: module 'myFramework.source.posgresql.connect' has no attribute 'getConnection'
[2024-07-10T20:09:20.189+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T200918, end_date=20240710T200920
[2024-07-10T20:09:20.242+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task customer (module 'myFramework.source.posgresql.connect' has no attribute 'getConnection'; 96)
[2024-07-10T20:09:20.294+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:09:20.422+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:15:06.658+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.679+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.681+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:15:06.724+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:15:06.743+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-10T20:15:06.768+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgq8nvpd7']
[2024-07-10T20:15:06.775+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask customer
[2024-07-10T20:15:06.916+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host c782b552e7b5
[2024-07-10T20:15:07.790+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:15:08.220+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:15:08.362+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:15:08.363+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:15:08.517+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements
[2024-07-10T20:15:08.535+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T201506, end_date=20240710T201508
[2024-07-10T20:15:08.577+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task customer (Length mismatch: Expected axis has 0 elements, new values have 10 elements; 99)
[2024-07-10T20:15:08.622+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:15:08.675+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:19:53.625+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.650+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.659+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:19:53.704+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:19:53.715+0000] {standard_task_runner.py:60} INFO - Started process 101 to run task
[2024-07-10T20:19:53.728+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp51ori1_3']
[2024-07-10T20:19:53.745+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask customer
[2024-07-10T20:19:53.907+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host dcd5a91c9a96
[2024-07-10T20:19:54.914+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:19:54.995+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:19:55.056+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:19:55.057+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:19:55.160+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements
[2024-07-10T20:19:55.178+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T201953, end_date=20240710T201955
[2024-07-10T20:19:55.195+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task customer (Length mismatch: Expected axis has 0 elements, new values have 10 elements; 101)
[2024-07-10T20:19:55.242+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:19:55.273+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:25:52.207+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.254+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:25:52.298+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:25:52.352+0000] {standard_task_runner.py:60} INFO - Started process 134 to run task
[2024-07-10T20:25:52.371+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpbu7iccaq']
[2024-07-10T20:25:52.375+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask customer
[2024-07-10T20:25:52.513+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host d72f5bf26a9d
[2024-07-10T20:25:53.643+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:25:53.786+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:25:53.886+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:25:53.888+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:25:53.926+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements
[2024-07-10T20:25:53.960+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T202552, end_date=20240710T202553
[2024-07-10T20:25:53.972+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task customer (Length mismatch: Expected axis has 0 elements, new values have 10 elements; 134)
[2024-07-10T20:25:54.010+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:25:54.098+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:33:41.808+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.830+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.831+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:33:41.876+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:33:41.885+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T20:33:41.902+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmy9czuh1']
[2024-07-10T20:33:41.916+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask customer
[2024-07-10T20:33:42.063+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host d0a0151057b2
[2024-07-10T20:33:43.253+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:33:43.319+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:33:43.401+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:33:43.404+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:33:43.554+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 60, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema, FilterColumn, '2007-02-15', '2007-02-16')
  File "/app/myFramework/utils/utils.py", line 57, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements
[2024-07-10T20:33:43.578+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T203341, end_date=20240710T203343
[2024-07-10T20:33:43.627+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task customer (Length mismatch: Expected axis has 0 elements, new values have 10 elements; 96)
[2024-07-10T20:33:43.674+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:33:43.714+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:36:57.525+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.533+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.535+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:36:57.554+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:36:57.564+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T20:36:57.586+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8hbkwtk5']
[2024-07-10T20:36:57.592+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask customer
[2024-07-10T20:36:57.785+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host dca83dd4e715
[2024-07-10T20:36:59.373+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:36:59.440+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:36:59.506+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:36:59.510+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:36:59.547+0000] {logging_mixin.py:188} INFO - not data at the period
[2024-07-10T20:36:59.551+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 28, in execute
    SqlToStaging().create_incremental().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 63, in some_function
    if sourceDF is not None:
UnboundLocalError: local variable 'sourceDF' referenced before assignment
[2024-07-10T20:36:59.584+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T203657, end_date=20240710T203659
[2024-07-10T20:36:59.600+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task customer (local variable 'sourceDF' referenced before assignment; 96)
[2024-07-10T20:36:59.674+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:36:59.720+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:40:14.016+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:14.036+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:14.041+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:40:14.070+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): customer> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:40:14.086+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-10T20:40:14.091+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'customer', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppcdf_g7i']
[2024-07-10T20:40:14.106+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask customer
[2024-07-10T20:40:14.295+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.customer scheduled__2024-07-09T00:00:00+00:00 [running]> on host 2bc01acfbd3e
[2024-07-10T20:40:15.107+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='customer' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:40:15.180+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'customer' and Stage = 'sqltostaging'
[2024-07-10T20:40:15.274+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0  15        customer    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:40:15.278+0000] {logging_mixin.py:188} INFO - select T.* from dvdrental.public.customer T where last_update >= '2007-02-15' and last_update < '2007-02-16' 
[2024-07-10T20:40:15.472+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T20:40:15.492+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=customer, execution_date=20240709T000000, start_date=20240710T204014, end_date=20240710T204015
[2024-07-10T20:40:15.552+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T20:40:15.569+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
