[2024-07-02T18:45:20.941+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.actor manual__2024-07-02T18:45:18.498280+00:00 [queued]>
[2024-07-02T18:45:21.003+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.actor manual__2024-07-02T18:45:18.498280+00:00 [queued]>
[2024-07-02T18:45:21.004+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T18:45:21.050+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): actor> on 2024-07-02 18:45:18.498280+00:00
[2024-07-02T18:45:21.086+0000] {standard_task_runner.py:60} INFO - Started process 226 to run task
[2024-07-02T18:45:21.114+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'actor', 'manual__2024-07-02T18:45:18.498280+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb7q7_z3k']
[2024-07-02T18:45:21.131+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask actor
[2024-07-02T18:45:21.306+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.actor manual__2024-07-02T18:45:18.498280+00:00 [running]> on host 5b7251376729
[2024-07-02T18:45:21.514+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='actor' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T18:45:18.498280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T18:45:18.498280+00:00'
[2024-07-02T18:45:21.517+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T18:45:21.527+0000] {logging_mixin.py:188} INFO - table: actor
[2024-07-02T18:45:21.529+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:actor
[2024-07-02T18:45:21.531+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 25, in some_function
    sourceDF = getDF(yaml.getSourceDBName(), yaml.getTSourceTableName(),yaml.getSourceSchema())
  File "/app/myFramework/utils/readYaml.py", line 25, in getSourceDBName
    return self.getYaml()['SourceDBName']
  File "/app/myFramework/utils/readYaml.py", line 15, in getYaml
    with open(yaml_file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/app/conf/sqltostaging/FULL.yaml'
[2024-07-02T18:45:21.556+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=actor, execution_date=20240702T184518, start_date=20240702T184520, end_date=20240702T184521
[2024-07-02T18:45:22.107+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task actor ([Errno 2] No such file or directory: '/app/conf/sqltostaging/FULL.yaml'; 226)
[2024-07-02T18:45:22.145+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T18:45:23.059+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
