[2024-07-03T18:57:43.417+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:57:43.445+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:57:43.447+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T18:57:43.459+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T18:57:43.475+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2024-07-03T18:57:43.486+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp630smxnd']
[2024-07-03T18:57:43.507+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask city
[2024-07-03T18:57:43.649+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host df9727a9ba29
[2024-07-03T18:57:44.552+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T18:57:44.565+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T18:57:44.568+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T18:57:44.574+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T18:57:44.604+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-03T18:57:44.607+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T18:57:44.622+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T185743, end_date=20240703T185744
[2024-07-03T18:57:44.726+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T18:57:44.770+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T18:59:06.283+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:59:06.310+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T18:59:06.316+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T18:59:06.375+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T18:59:06.388+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-03T18:59:06.410+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4_1s2pnz']
[2024-07-03T18:59:06.420+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask city
[2024-07-03T18:59:06.590+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 1eca196ca799
[2024-07-03T18:59:07.566+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T18:59:07.571+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T18:59:07.573+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T18:59:07.579+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T18:59:07.632+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T18:59:07.663+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T185906, end_date=20240703T185907
[2024-07-03T18:59:07.695+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 99)
[2024-07-03T18:59:07.731+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T18:59:07.779+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:04:29.036+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:04:29.105+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:04:29.133+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:04:29.229+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:04:29.242+0000] {standard_task_runner.py:60} INFO - Started process 106 to run task
[2024-07-03T19:04:29.318+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7hywgf4e']
[2024-07-03T19:04:29.345+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask city
[2024-07-03T19:04:29.587+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 1e717689b816
[2024-07-03T19:04:30.185+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:04:30.193+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:04:30.198+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:04:30.200+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:04:31.540+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:04:31.555+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T190429, end_date=20240703T190431
[2024-07-03T19:04:31.574+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 106)
[2024-07-03T19:04:31.615+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:04:31.665+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:07:23.683+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:07:23.693+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:07:23.693+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:07:23.706+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:07:23.736+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2024-07-03T19:07:23.729+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg087555v']
[2024-07-03T19:07:23.753+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask city
[2024-07-03T19:07:23.972+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 543ad6da9cd9
[2024-07-03T19:07:24.951+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:07:24.954+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:07:24.959+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:07:24.961+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:07:25.009+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:07:25.069+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T190723, end_date=20240703T190725
[2024-07-03T19:07:25.123+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 103)
[2024-07-03T19:07:25.157+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:07:25.227+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:11:45.058+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:11:45.075+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:11:45.079+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:11:45.110+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:11:45.134+0000] {standard_task_runner.py:60} INFO - Started process 131 to run task
[2024-07-03T19:11:45.186+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpozdujz2e']
[2024-07-03T19:11:45.221+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask city
[2024-07-03T19:11:45.404+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 7c298ace0001
[2024-07-03T19:11:46.270+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:11:46.274+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:11:46.277+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:11:46.280+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:11:46.281+0000] {logging_mixin.py:188} INFO - city sqltostaging
[2024-07-03T19:11:46.367+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:11:46.432+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T191145, end_date=20240703T191146
[2024-07-03T19:11:46.500+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 131)
[2024-07-03T19:11:46.560+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:11:46.596+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:17:15.681+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:17:15.691+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:17:15.698+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:17:15.735+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:17:15.749+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-03T19:17:15.770+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyjox0f17']
[2024-07-03T19:17:15.780+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask city
[2024-07-03T19:17:15.989+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 55c1c604b2f4
[2024-07-03T19:17:17.290+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:17:17.294+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:17:17.296+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:17:17.301+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:17:17.304+0000] {logging_mixin.py:188} INFO - city sqltostaging
[2024-07-03T19:17:17.307+0000] {logging_mixin.py:188} INFO - sqltostaging city
[2024-07-03T19:17:17.310+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T19:17:17.333+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T191715, end_date=20240703T191717
[2024-07-03T19:17:17.375+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T19:17:17.392+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:21:11.325+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:21:11.352+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:21:11.358+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:21:11.405+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:21:11.411+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-03T19:21:11.430+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmps5osdj49']
[2024-07-03T19:21:11.441+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask city
[2024-07-03T19:21:11.650+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 048fbe570e70
[2024-07-03T19:21:12.695+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:21:12.733+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:21:12.741+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:21:12.749+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:21:12.776+0000] {logging_mixin.py:188} INFO - city sqltostaging
[2024-07-03T19:21:12.822+0000] {logging_mixin.py:188} INFO - sqltostaging city
[2024-07-03T19:21:12.824+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'sqltostaging' and Stage = 'city'
[2024-07-03T19:21:12.908+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table(f"{table}", f"{stage}")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:21:12.958+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T192111, end_date=20240703T192112
[2024-07-03T19:21:13.042+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 96)
[2024-07-03T19:21:13.076+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:21:13.140+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:27:20.598+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:27:20.637+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:27:20.648+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:27:20.711+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:27:20.730+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-07-03T19:27:20.758+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9o3n_b4j']
[2024-07-03T19:27:20.774+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask city
[2024-07-03T19:27:20.929+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host be8a642b7fa1
[2024-07-03T19:27:22.079+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:27:22.085+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:27:22.087+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:27:22.090+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:city
[2024-07-03T19:27:22.095+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'staff' and Stage = 'sqltostaging'
[2024-07-03T19:27:22.144+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 31, in some_function
    df = get_data_from_conf_table("staff", "sqltostaging")
  File "/app/myFramework/utils/utils.py", line 143, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-03T19:27:22.167+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=city, execution_date=20240702T000000, start_date=20240703T192720, end_date=20240703T192722
[2024-07-03T19:27:22.175+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task city (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 92)
[2024-07-03T19:27:22.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:27:22.221+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:31:15.753+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:31:15.777+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:31:15.783+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:31:15.817+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:31:15.857+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-03T19:31:15.876+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0bhx91lg']
[2024-07-03T19:31:15.893+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask city
[2024-07-03T19:31:16.076+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 3aa24a0be289
[2024-07-03T19:31:17.286+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:31:17.295+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:31:17.296+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:31:17.298+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:31:17.299+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'staff' and Stage = 'SqlToStaging'
[2024-07-03T19:31:17.344+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-03T19:31:17.347+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T19:31:17.356+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T193115, end_date=20240703T193117
[2024-07-03T19:31:17.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T19:31:17.442+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:33:30.549+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:33:30.582+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:33:30.590+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:33:30.615+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:33:30.621+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-03T19:33:30.636+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyxg5jdo1']
[2024-07-03T19:33:30.648+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask city
[2024-07-03T19:33:30.763+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 90f97448b910
[2024-07-03T19:33:31.408+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:33:31.411+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:33:31.414+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:33:31.417+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:33:31.420+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'SqlToStaging'
[2024-07-03T19:33:31.458+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    city
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-03T19:33:31.461+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-03T19:33:31.478+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T193330, end_date=20240703T193331
[2024-07-03T19:33:31.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-03T19:33:31.721+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:45:39.304+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:45:39.323+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:45:39.324+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:45:39.356+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:45:39.372+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2024-07-03T19:45:39.391+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg5pwgp1x']
[2024-07-03T19:45:39.397+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask city
[2024-07-03T19:45:39.607+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 2d80eee2aa9e
[2024-07-03T19:45:40.739+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:45:40.761+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:45:40.772+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:45:40.783+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:45:40.788+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'SqlToStaging'
[2024-07-03T19:45:40.916+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 32, in some_function
    sourceDF = getDF(df['sourcedbname'], df['sourcetablename'], df['sourceschema'])
  File "/app/myFramework/utils/utils.py", line 22, in getDF
    cur = conn.getCursor(source_dbname)
  File "/app/myFramework/source/posgresql/connect.py", line 6, in getCursor
    conn = psycopg2.connect(database = dbname,
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (172.28.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist

[2024-07-03T19:45:40.993+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T194539, end_date=20240703T194540
[2024-07-03T19:45:41.037+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task city (connection to server at "postgres_db" (172.28.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist
; 142)
[2024-07-03T19:45:41.082+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:45:41.252+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:51:24.114+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:51:24.129+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:51:24.131+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:51:24.184+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:51:24.210+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-03T19:51:24.242+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpk7b4_eq2']
[2024-07-03T19:51:24.268+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask city
[2024-07-03T19:51:24.404+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host f02b6fe92b0c
[2024-07-03T19:51:25.582+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:51:25.595+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:51:25.618+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:51:25.621+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:51:25.632+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'SqlToStaging'
[2024-07-03T19:51:25.691+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 0    city
Name: sourcetablename, dtype: object 0    public
Name: sourceschema, dtype: object
[2024-07-03T19:51:25.713+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 34, in some_function
    sourceDF = getDF(df['sourcedbname'], df['sourcetablename'], df['sourceschema'])
  File "/app/myFramework/utils/utils.py", line 22, in getDF
    cur = conn.getCursor(source_dbname)
  File "/app/myFramework/source/posgresql/connect.py", line 6, in getCursor
    conn = psycopg2.connect(database = dbname,
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (172.29.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist

[2024-07-03T19:51:25.731+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T195124, end_date=20240703T195125
[2024-07-03T19:51:25.747+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task city (connection to server at "postgres_db" (172.29.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist
; 97)
[2024-07-03T19:51:25.784+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:51:25.834+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:57:27.462+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:57:27.492+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:57:27.500+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:57:27.550+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:57:27.586+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-07-03T19:57:27.600+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp96pc1n9m']
[2024-07-03T19:57:27.621+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask city
[2024-07-03T19:57:27.823+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 94f9954c2898
[2024-07-03T19:57:28.040+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:57:28.049+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:57:28.054+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:57:28.065+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:57:28.065+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'SqlToStaging'
[2024-07-03T19:57:29.155+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SourceSchema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 32, in some_function
    print(df['sourcedbname'], df['sourcetablename'], df['SourceSchema'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'SourceSchema'
[2024-07-03T19:57:29.180+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T195727, end_date=20240703T195729
[2024-07-03T19:57:29.247+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task city ('SourceSchema'; 90)
[2024-07-03T19:57:29.288+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:57:29.356+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:59:31.728+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:59:31.752+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-03T19:59:31.753+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-03T19:59:31.795+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): city> on 2024-07-02 00:00:00+00:00
[2024-07-03T19:59:31.802+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-03T19:59:31.808+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'city', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp89dqxrw2']
[2024-07-03T19:59:31.844+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask city
[2024-07-03T19:59:32.041+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.city scheduled__2024-07-02T00:00:00+00:00 [running]> on host 091922596b62
[2024-07-03T19:59:33.217+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='city' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-03T19:59:33.231+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-03T19:59:33.232+0000] {logging_mixin.py:188} INFO - table: city
[2024-07-03T19:59:33.232+0000] {logging_mixin.py:188} INFO - 
 stage: SqlToStaging 
 table:city
[2024-07-03T19:59:33.243+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'city' and Stage = 'SqlToStaging'
[2024-07-03T19:59:33.309+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 0    city
Name: sourcetablename, dtype: object 0    public
Name: sourceschema, dtype: object
[2024-07-03T19:59:33.333+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 34, in some_function
    sourceDF = getDF(df['sourcedbname'], df['sourcetablename'], df['sourceschema'])
  File "/app/myFramework/utils/utils.py", line 22, in getDF
    cur = conn.getCursor(source_dbname)
  File "/app/myFramework/source/posgresql/connect.py", line 6, in getCursor
    conn = psycopg2.connect(database = dbname,
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (192.168.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist

[2024-07-03T19:59:33.347+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=city, execution_date=20240702T000000, start_date=20240703T195931, end_date=20240703T195933
[2024-07-03T19:59:33.360+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task city (connection to server at "postgres_db" (192.168.0.5), port 9999 failed: FATAL:  database "0    dvdrental
Name: sourcedbname, dtype: object" does not exist
; 88)
[2024-07-03T19:59:33.403+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-03T19:59:33.489+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
